apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: luwi54trs-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fc0bb04f88.gikd.p3.openshiftapps.com/rhtap/rhtap-qe:3add0bf66ba04b1542981fb3a246a87839d77f4e@sha256:acfddfef54ebfec81a132f780ca6281073da56b22f2aed87b82cf3ba79d84316
          name: container-image
